// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;


class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
      apiKey: "AIzaSyAGYKDdjNjVe13M6JUGmRNVe6PEdV8QpJY",
      authDomain: "quatr-69067.firebaseapp.com",
      projectId: "quatr-69067",
      storageBucket: "quatr-69067.appspot.com",
      messagingSenderId: "658664071138",
      appId: "1:658664071138:web:f2eaa639b422ca087b23bb",
      measurementId: "G-X7KY2XWFBD"
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQbNMeq-42ToMm3FNHt4l8Un5aPKGO0TE',
    appId: '1:658664071138:android:3e6350642ddcec037b23bb',
    messagingSenderId: '658664071138',
    projectId: 'quatr-69067',
    storageBucket: 'quatr-69067.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQbNMeq-42ToMm3FNHt4l8Un5aPKGO0TE',
    appId: '1:658664071138:ios:6755be05e38b93497b23bb',
    messagingSenderId: '658664071138',
    projectId: 'quatr-69067',
    storageBucket: 'quatr-69067.appspot.com',
    iosBundleId: 'com.quatrng.com.quatr',
  );
}
